CREATE DATABASE IF NOT EXISTS stocks_db;
USE stocks_db;

CREATE TABLE IF NOT EXISTS simbolos_sp500 (
    id INT AUTO_INCREMENT PRIMARY KEY,precios
    simbolo VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS precios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    simbolo VARCHAR(10) NOT NULL,
    precio VARCHAR(50) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);